### ISSUE TITLE
Compatability With HexChat

### ISSUE THREAD

**Issue by RobinGhost** [ftc2/interview-notify#8]
Hi, Is yourscript compatible with HexChat? I have it set up, but when it run the script only gets as far as this line the stops at:

2024-02-04 19:53:16 INFO: parser: using "Gatekeeper.log"

Here is my execution command:

python interview_notify.py --topic interview --log-dir "M:\Programs\HexChatPortable\Data\settings\logs\New Network" --nick xxxxxx --check-bot-nicks

Thanks for the effort

**Comment by ftc2** [comment]
well, it should be parsing a log of the interview channel (`Gatekeeper.log` does not sound like that). is such a log file present?

**Comment by RobinGhost** [comment]
Thanks for the quick response.
Here is my gatekeeper log.
Cheers

[Gatekeeper.log](https://github.com/ftc2/interview-notify/files/14158526/Gatekeeper.log)

**Comment by ftc2** [comment]
again, that is not the log for the interview channel. that is your private message log with Gatekeeper. the script needs to parse the interview channel log.

**Comment by RobinGhost** [comment]
ah sorry, you meant this log file.
[#red-invites.log](https://github.com/ftc2/interview-notify/files/14158588/red-invites.log)
